spring:
  datasource:
    url: jdbc:mysql://localhost:3309/ssi
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
